#Exercício nº 3

In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge
import matplotlib.pyplot as plt
import altair as alt 

In [ ]:
eixos_df = pd.read_csv("exercicio-tres.csv")
eixos_df.head()

eixo_x  eixo_y  classe
0    1.16    7.04       0
1    7.21    7.55       1
2    2.36    8.76       0
3    4.31    6.81       1
4    0.41    9.49       0

In [ ]:
X = np.array(eixos_df.drop(['classe'], 1))
y = np.array(eixos_df['classe'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [ ]:
for c in eixos_df.columns:
    eixos_df[c] = (eixos_df[c].max() - eixos_df[c]) / (eixos_df[c].max() - eixos_df[c].min())

In [ ]:
eixos_df.head()

eixo_x    eixo_y  classe
0  0.110294  0.085821     0.0
1  1.000000  0.276119     1.0
2  0.286765  0.727612     0.0
3  0.573529  0.000000     1.0
4  0.000000  1.000000     0.0

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size = 0.3, random_state = 0) 

1. Utilize o K-NN para o valor de k: 1.

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(X_treino, y_treino)
predictions1 = knn.predict(X_treino)

print(predictions1)

[1. 0. 0. 0. 0. 1. 0.]


2. Utilize o K-NN para o valor de k: 3.

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_treino, y_treino)
predictions3 = knn.predict(X_treino)

print(predictions3)

[0. 0. 0. 0. 0. 0. 0.]


3. Utilize o K-NN para o valor de k: 5.

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_treino, y_treino)
predictions5 = knn.predict(X_treino)

print(predictions5)

[0. 0. 0. 0. 0. 0. 0.]


4. Utilize o K-NN para o valor de k: 7.

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 7)
knn.fit(X_treino, y_treino)
predictions7 = knn.predict(X_treino)

print(predictions7)

[0. 0. 0. 0. 0. 0. 0.]


5. Realize uma projeção de dispersão para visualizar os dados.

In [ ]:
alt.Chart(eixos_df).mark_point().encode( 
    x='eixo_x', 
    y='eixo_y'
) 

alt.Chart(...)

6. Anote a taxa de acerto (acurácia).

In [ ]:
acuracia_treino = knn.score(X_treino, y_treino)
print(acuracia_treino)

0.7142857142857143


In [ ]:
acuracia_teste = knn.score(X_teste, y_teste)
print(acuracia_teste)

0.0
